config/routes.rb
Joslink::Application.routes.draw do

scope "(:locale)", :locale => /en|fr/ do
  resources :system_notes do as_routes end

  resources :cities do as_routes end

  get "sessions/new"
  get "sessions/safe_page", :as => 'safe_page'
  get '/:controller/export', :action => 'export'
  match '/:controller/import', :action => 'import'

  get 'admin/site_settings' => 'site_settings#edit', :as=>'site_settings'
  get 'admin/site_settings/index' => 'site_settings#index', :as=>'index_site_settings'
  put 'admin/site_settings' => 'site_settings#update', :as=>'update_site_settings'
  resources :app_logs do as_routes end
  resources :bloodtypes do as_routes end
  resources :incoming_mails do as_routes end
  resources :countries do as_routes end
  match 'groups/member_count'
  resources :groups do as_routes end
  resources :incoming_mails do as_routes end
  resources :locations do as_routes end
  match "sent_messages/clickatell_status",  :to => "sent_messages#update_status_clickatell"
  get "messages/:id/followup", :to => "messages#followup"
  match "messages/:id/followup_send", :to => "messages#followup_send"
  get "members/wife_select", :to => 'members#wife_select'
  resources :members do as_routes end
  resources :messages do as_routes end
  resources :sent_messages do as_routes end
  resources :sms
  match 'reports/index' => 'reports#index', :as => 'reports'
  match 'reports/directory' => 'reports#directory', :as => 'directory'

  get   '/login', :to => 'sessions#new', :as => :sign_in
  get   '/signin', :to => 'sessions#new', :as => :sign_in  # signin is just an alias for login
  get '/logout', :to => 'sessions#destroy', :as => :sign_out
  get '/signout', :to => 'sessions#destroy', :as => :sign_out  # signout is just an alias for logout
  match '/auth/:provider/callback', :to => 'sessions#create', :as => :create_session
  match '/signin_test', :to => 'sessions#create', :as => :create_test_session
  match '/auth/failure', :to => 'sessions#failure'
  get '/setup', :to => 'setup#initialize', :as => :initialize
  post '/setup', :to => 'setup#initialize_save'

  match '/:locale' => 'members#index'
  get "/home", :to => "members#index", :as => :home
  root :to => "members#index"
  

end
end

app/models/site_setting.rb
# == Schema Information
# Schema version: 20110604193420
#
# Table name: site_settings
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  value      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class SiteSetting < ActiveRecord::Base
# Taken from Configurable_Engine by Paulca
# https://github.com/paulca/configurable_engine
  
  def self.defaults
    HashWithIndifferentAccess.new(
      YAML.load_file(
        Rails.root.join('config', 'site_settings.yml')
      )
    )
  end
  
  def self.keys
    self.defaults.collect { |k,v| k.to_s }.sort
  end
  
  def self.[](key)
    unless self.defaults[key]
      raise "Site settings key '#{key}' not found in config/site_settings.yml"
    end
    value = find_by_name(key).try(:value) || (self.defaults[key])[:default]
    case self.defaults[key][:type]
    when 'boolean'
      [true, 1, "1", "t", "true"].include?(value)
    when 'decimal'
      BigDecimal.new(value.to_s)
    when 'integer'
      value.to_i
    when 'list'
      return value if value.is_a?(Array)
      value.split("\n").collect{ |v| v.split(',') }
    else
      value
    end
  end
  
  def self.method_missing(name, *args)
    name_stripped = name.to_s.gsub('?', '')
    if self.keys.include?(name_stripped)
      self[name_stripped]
    else
      super
    end
  end
  
end

app/controllers/site_settings_controller.rb
class SiteSettingsController < ApplicationController
  protect_from_forgery

#  before_filter :authenticate_admin #, :only => [:edit, :update]
#  include AuthenticationHelper
  include ApplicationHelper
  include SessionsHelper
  load_and_authorize_resource
  
  layout 'application'

  def edit
  end

  def index
  end

  def update
    SiteSetting.keys.each do |key|
      SiteSetting.find_or_create_by_name(key).
                   update_attribute(:value,params[key])
    end
    flash[:notice] = "Settings saved"
    redirect_to site_settings_path
  end
end

app/helpers/site_settings_helper.rb
module SiteSettingsHelper

  def settings_field(field, params={})
    label = params[:label] || field.to_s.humanize
    field_type = params[:field_type]
    boolean = field_type == :boolean
    label << '?' if field_type == :boolean
    input_field = case
      when field.to_s =~ /password/ || params[:password]
        password_field_tag(field, SiteSetting[field])
      when field_type == :boolean
        check_box_tag(field, SiteSetting[field])
      when params[:choices]
        
        select_tag(field, options_for_select(params[:choices], SiteSetting[field]))
      else
        text_field_tag(field, SiteSetting[field])
    end
    ("<div class='site_setting' id='#{field}_form'>".html_safe +
    label_tag(field, label) +
    (field_type == :boolean ? '' : "<br>".html_safe) +
    input_field +
    "</div>".html_safe
    )
  end

end

app/views/site_settings/edit.html.haml
<script>
$(function() {
$( "#tabs" ).tabs();
});
</script>
<div >
%h2= t('.title') 
%p= t('.be_sure_to_save')
#tabs
  %ul
    %li= link_to t(".site"), "#tabs-site"
    %li= link_to t(".tab-sms"), "#tabs-sms"
    %li= link_to t(".tab-email"), "#tabs-email"
    %li= link_to t(".tab-notifications"), "#tabs-notifications"
    %li= link_to t(".tab-maint"), "#tabs-maint"
    %li= link_to t(".tab-other"), "#tabs-other"
  .active-scaffold.site_settings
    = form_tag(update_site_settings_path, :method => :put) do 
      #tabs-site
        = settings_field(:organization)
        = settings_field(:org_system_name)
        = settings_field(:base_url)
        = settings_field(:message_id_string)
      #tabs-sms
        #sms-default
          = settings_field(:incoming_sms_number)
          = settings_field(:incoming_voice_number)
          %h4=  t('.default_outgoing_sms_gateway')
          = settings_field(:default_outgoing_sms_gateway, :label => '',
          :choices => [['Twilio'], ['Clickatell']])
          %h4=  t('.alternate_outgoing_sms_gateway')
          = settings_field(:alternate_outgoing_sms_gateway, :label => '',
          :choices => [['None', ''], ['Twilio'], ['Clickatell']])
        #sms-service-1
          %h4 Clickatell 
          = settings_field(:clickatell_user_name, :label=> t('.clickatell_user_name'))
          = settings_field(:clickatell_password, :label=> t('.clickatell_password'))
          = settings_field(:clickatell_api_id, :label=>'Clickatell API ID')
        #sms-service-2
          %h4 Twilio
          = settings_field(:twilio_account_sid, :label=> t('.twilio_account_sid'))
          = settings_field(:twilio_auth_token, :password=>true, :label=> t('.twilio_auth_token'))
          = settings_field(:twilio_api_version, :label=> t('.twilio_api_version'))
          = settings_field(:twilio_phone_number, :label => t('.twilio_phone_number'))
          = settings_field(:twilio_background, :label => t('.twilio_background'), :choices=>[[t('None'), ''], ['DelayedJob'], ['IronWorker']])
      #tabs-email
        %p= t('.sendgrid_instructions')
        = settings_field(:base_email_address)
        = settings_field(:sendgrid_user_name, :label=> t('.sendgrid_user_name'))
        = settings_field(:sendgrid_password, :label=> t('.sendgrid_password'))
      #tabs-notifications
        %h4= t('.contact_updates')
        %p= t('.contact_update_instructions') 
        = settings_field(:contact_update_recipients, :label => t('.contact_update_recipients'))
        %br
        = settings_field(:default_news_update_expiration)
      #tabs-maint
        %p= t('.cleanup_instructions')
        %table#cleanup_table
          %tr
            %th= t('Log')
            %th= t('Messages')
            %th= t('Sent_Messages')
          %tr
            %td= t('.log_explanation')
            %td= t('.message_log_explanation')
            %td= t('.sent_message_log_explanation')
          %tr
            %td= settings_field(:log_max_records, :label=> t('.log_max_records'))  
            %td= settings_field(:messages_max_records, :label=> t('.messages_max_records'))
            %td= settings_field(:sent_messages_max_records, :label=> t('.sent_messages_max_records'))
          %tr
            %td= settings_field(:log_retention_period, :label=> t('.log_retention_period'))
            %td= settings_field(:messages_retention_period, :label=> t('.messages_retention_period'))
            %td= settings_field(:sent_messages_retention_period, :label=> t('.sent_messages_retention_period'))
      #tabs-other
        %h4= t('Auto-update')
        %p= t('.auto_update_instructions')
        = settings_field(:auto_update_in_country_status, :label => t('.auto_update_in_country_status'), :choices=> [[t('Yes'), 1], [t('No'), 0]])
        = settings_field(:directory_title)
        = settings_field(:email_command_delimiter)
      %hr
      = submit_tag t('Save')
    

app/views/site_settings/index.html.haml
.active-scaffold.site_settings
  %h2 Site Settings
  %h3 Configuration file (default)
  - SiteSetting.defaults.each do |s| 
    = "#{s[0]} (#{s[1][:default]})<br>".html_safe
  %h3 Found in database table  
  - SiteSetting.all.each do |s| 
    = "#{s.name} => #{s.value}<br>".html_safe