config/routes.rb
Joslink::Application.routes.draw do

scope "(:locale)", :locale => /en|fr/ do
  resources :system_notes do as_routes end

  resources :cities do as_routes end

  get "sessions/new"
  get "sessions/safe_page", :as => 'safe_page'
  get '/:controller/export', :action => 'export'
  match '/:controller/import', :action => 'import'

  get 'admin/site_settings' => 'site_settings#edit', :as=>'site_settings'
  get 'admin/site_settings/index' => 'site_settings#index', :as=>'index_site_settings'
  put 'admin/site_settings' => 'site_settings#update', :as=>'update_site_settings'
  resources :app_logs do as_routes end
  resources :bloodtypes do as_routes end
  resources :incoming_mails do as_routes end
  resources :countries do as_routes end
  match 'groups/member_count'
  resources :groups do as_routes end
  resources :incoming_mails do as_routes end
  resources :locations do as_routes end
  match "sent_messages/clickatell_status",  :to => "sent_messages#update_status_clickatell"
  get "messages/:id/followup", :to => "messages#followup"
  match "messages/:id/followup_send", :to => "messages#followup_send"
  get "members/wife_select", :to => 'members#wife_select'
  resources :members do as_routes end
  resources :messages do as_routes end
  resources :sent_messages do as_routes end
  resources :sms
  match 'reports/index' => 'reports#index', :as => 'reports'
  match 'reports/directory' => 'reports#directory', :as => 'directory'

  get   '/login', :to => 'sessions#new', :as => :sign_in
  get   '/signin', :to => 'sessions#new', :as => :sign_in  # signin is just an alias for login
  get '/logout', :to => 'sessions#destroy', :as => :sign_out
  get '/signout', :to => 'sessions#destroy', :as => :sign_out  # signout is just an alias for logout
  match '/auth/:provider/callback', :to => 'sessions#create', :as => :create_session
  match '/signin_test', :to => 'sessions#create', :as => :create_test_session
  match '/auth/failure', :to => 'sessions#failure'
  get '/setup', :to => 'setup#initialize', :as => :initialize
  post '/setup', :to => 'setup#initialize_save'

  match '/:locale' => 'members#index'
  get "/home", :to => "members#index", :as => :home
  root :to => "members#index"
  

end
end

app/views/shared/_side_menu.html.haml
- if signed_in? 
  %h5= t('Main_Menu')
  %ul.links
    %li 
      = t(:Choose)
      = link_to t(:english), change_locale_to(:en)
      = t(:or)
      = link_to t(:french), change_locale_to(:fr)
    %li= link_to t('side_menu.edit_your_user_info'), edit_member_path(current_user, :locale=>I18n.locale)
    %li= link_to t('side_menu.sign_out'), sign_out_path 
    - if current_user.roles_include? :member
      %li= link_to t('side_menu.members'), members_path 
      %li= link_to t('side_menu.create_new_message'), new_message_path
      %li= link_to t('side_menu.reports'), reports_path
      %li= link_to t('side_menu.system_notices'), system_notes_path
    - if current_user.roles_include? :moderator
      %h5= t(:Moderators)
      %li= link_to t('side_menu.message_list'), messages_path
      %li= link_to t('side_menu.groups'), groups_path
      %li= link_to t('side_menu.log'), '/app_logs'
    - if current_user.roles_include? :administrator
      %h5= t('Option_tables')
      %li= link_to t('side_menu.bloodtypes'), bloodtypes_path 
      %li= link_to t('side_menu.cities'), cities_path 
      %li= link_to t('side_menu.countries'), countries_path 
      %li= link_to t('side_menu.locations'), locations_path 
      %hr
      %h5= t('Admin_tasks')
      %li= link_to t('side_menu.settings'), site_settings_path(:locale => I18n.locale)
  %hr
- else 